---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrocd-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agrocd-application
  template:
    metadata:
      labels:
        app: agrocd-application
    spec:
      containers:
      - name: agrocd-application
        # image: ziemieu86/agrocd-application:latest
        image: image update
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: agrocd-application-service
spec:
  selector:
    app: agrocd-application
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer

